#---------------------------------#
#    environment configuration    #
#---------------------------------#

init:
  - git config --global core.autocrlf true


#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - dnu restore

configuration:
  - debug
  - release

build:
  parallel: true
  project: src\CamlBuilder.sln


#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - CamlBuilder.UnitTests.dll