init:
  - git config --global core.autocrlf true


before_build:
  - dotnet restore


configuration:
  - debug
  - release


build_script:
  - dotnet pack src\CamlBuilder\project.json --configuration %configuration% --output out_bin
  - dotnet build src\CamlBuilder.UnitTests\project.json --configuration %configuration% --output out_tests --framework netcoreapp1.0


test_script:
  - dotnet test src\CamlBuilder.UnitTests\project.json


artifacts:
  - path: out_bin\$(configuration)\*.nupkg
    name: nuget_packages


deploy:
  - provider: NuGet
    api_key: 
      secure: sQplMyrjV8N58rccFtWBFZcsjJy6iHKKP9DbSxRAds10jrfshfM+JorTBMyN8wOs
    on:
      branch: master
      appveyor_repo_tag: true
      configuration: release
    skip_symbols: true
    artifact: nuget_packages