init:
  - dotnet --info
  - git config --global core.autocrlf true


configuration:
  - debug
  - release


build_script:
  - dotnet pack src\CamlBuilder\CamlBuilder.csproj --configuration %configuration% --output ..\..\out_bin


test_script:
  - dotnet test tests\CamlBuilder.UnitTests\CamlBuilder.UnitTests.csproj


artifacts:
  - path: out_bin\*.nupkg
    name: nuget_packages


deploy:
  - provider: NuGet
    api_key: 
      secure: Q/dky+nYmx9bk3vd0qrvoFbPB6XN8wIenzVwmO1SDw3b8RphWExzhuoK6eLXUgaQ
    on:
      branch: master
      appveyor_repo_tag: true
      configuration: release
    skip_symbols: true
    artifact: nuget_packages