#---------------------------------#
#    environment configuration    #
#---------------------------------#

init:
  - git config --global core.autocrlf true


#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - dnu restore

configuration:
  - debug
  - release

build_script:
  - dnu build src\CamlBuilder\project.json --configuration $(configuration) --out out_bin
  - dnu build src\CamlBuilder.UnitTests\project.json --configuration $(configuration) --out out_tests


#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - dnx --project src\CamlBuilder.UnitTests\project.json run-tests